### ISSUE TITLE
Add shortkeys

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#101]
Please add shortkeys for commonly used actions:

Remove from posse (suggest ctrl+N, same as removing from a challenge in AGOT)

Trade goods to target dude (suggest ctrl+T)

Also I suggest to make one "Spawn token" group in the right-click menu with different options inside: Gunslinger, Nature, Ancestor.

**Comment by jayjester** [comment]
Also would really like to see a shortkey for:

Shootout: Stud
Shootout: Draw
High noon: Stud
High noon: Draw

**Comment by soulb1ight** [comment]
It would be great to have a shortkey for drawing to the draw hand that brings up the dialogue to enter in how many cards you would like to draw.
