### ISSUE TITLE
Huntsmen's Society

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#106]
Might be handy to script it so that when you target a dude and ctrl+z the Society, it would place a +1 Production counter on that dude automatically?

Adding ghost rock manually during upkeep requires more micro-management, and I think it's a good idea to avoid the right-click menu as much as possible.

**Comment by db0** [comment]
Really? I find it easier to either just quickly press Alt+P to add production, or to just take some extra GR before I press for upkeep. I can make it work with Ctrl+Z, but honestly why do two clicks (Target and Ctrl+Z) when you can just Alt+P instead?

**Comment by mplain** [comment]
You probably have big hands :)

My right hand rests on the mouse, my left hand on the far left side of the keyboard (WASD area). I can't press Alt+P without moving one of my hands. It's an ergonomy issue.

**Comment by db0** [comment]
i.e. you're too lazy to move your hands? :P
