### ISSUE TITLE
Lowball winner

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#109]
When lowball hands are revealed, the winner marker is assigned immediately. If the timing order actually matters (Pair of Six-Shooters vs. another cheatin' res), players have to scroll the log to see who won lowball last turn and now has the first chance to act.

Please make it so that the winner marker is only assigned when a player presses ctrl+W.

**Comment by db0** [comment]
Huh? It's not?

**Comment by mplain** [comment]
Emphasis on the word 'only'.
