### ISSUE TITLE
Den of Thieves

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#117]
1) If it possible to implement the discount for Grifters in the starting posse as well as new ones? Maybe make it trigger and give 1 gr every time a Grifter is played (similar to Flint's Amusements). Same with Monte Bank.

2) Would be nice if the React ability was automated, i.e. target a dude, ctrl+Z on the Den = gain 1 gr, put 1 bounty, spawn a Cheatin' marker, show in the log "Player used Den of Thieves to increase their hand rank by 1" (similar to Tommy Harden and Barton Everest).

**Comment by db0** [comment]
The ability should already be automated.

**Comment by mplain** [comment]
Ctrl+Z on the Den does nothing, says "not scripted".
