### ISSUE TITLE
The Extra Bet

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#121]
Please explain how to use this card's ability correctly.
There are no timing windows for it on Octgn.

**Comment by db0** [comment]
You use it instead of Ctrl+Q. Then you open your lowball hand and manipulate like a shootout.

**Comment by mplain** [comment]
It doesn't work this way.

![1](https://cloud.githubusercontent.com/assets/7605827/10650329/7de89a3a-7851-11e5-8de5-38d8da138e61.jpg)

**Comment by db0** [comment]
Something is weird, you're posting a lot of scripts that should be working. I'll take a look when I can

**Comment by db0** [comment]
Try now
