### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#125]
Consecration doesn't place bonus bullets and influence markers on the target.

**Comment by db0** [comment]
Fixed

**Comment by mplain** [comment]
If I'm reading this right
https://github.com/db0/Doomtown-Reloaded-OCTGN/commit/c378563f776b2a8df1378d11f3921538059a88e6
you now have Consecration coded as having difficulty 6, whereas it actially should be difficulty 7.

**Comment by db0** [comment]
Oops!
