### ISSUE TITLE
Make Jake Smiley's influence count towards the influence total in the lower bar

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#135]
Pretty much the only reason people check the lower bar is to see what happens during sundown anyway. Newer players tend to forget about Jake a lot, while it'd still be very convenient for experienced players. It's a win-win. Pretty please!

**Comment by mplain** [comment]
Jake Smiley now gets +2 influence markers when played, but not when you start him. So most decks are unaffected.

Maybe just changing his influence value to 2 would be simple and more effective, without any real drawbacks?

**Comment by db0** [comment]
NO because then it would show with 2 inf on the proxy card
