### ISSUE TITLE
Old Marge's Manor not automated

### ISSUE THREAD

**Issue by mysticpickle** [db0/Doomtown-Reloaded-OCTGN#137]
There doesn't seem to be any valid choices when I use card ability on Old Marge's Manor

![image](https://cloud.githubusercontent.com/assets/3962478/12766128/f6254fdc-c9b6-11e5-873f-1b1dc48c49c4.png)

**Comment by mplain** [comment]
And when you do use it, it actually removes all ghost rock that i placed on it manually.
