### ISSUE TITLE
Lowball glitches a lot after the new update

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#138]
Gives error messages, doesn't show ante, doesn't determine the winner.

![1](https://cloud.githubusercontent.com/assets/7605827/12794026/36cb091a-cac4-11e5-8e6b-4bdfe1dd312b.jpg)

**Comment by db0** [comment]
It works but you have to press f1 the first time. I'll fix this today but you can work with this until then
