### ISSUE TITLE
jansoz pratt ability gives errors

### ISSUE THREAD

**Issue by mysticpickle** [db0/Doomtown-Reloaded-OCTGN#141]
Jansoz Pratt's ability creates a pull and brings up a window to prompt for gadgets to fetch and dude to attach to but then causes error messages.  Also does not give booted dudes in the shootout as an option to attach the invented gadget to:

![image](https://cloud.githubusercontent.com/assets/3962478/12857028/c4b9dcd6-cbfc-11e5-9cf8-5c2f040e945f.png)

![image](https://cloud.githubusercontent.com/assets/3962478/12857036/ce9a8886-cbfc-11e5-9d3f-ae10a05a6566.png)

![image](https://cloud.githubusercontent.com/assets/3962478/12857048/deeee984-cbfc-11e5-8774-dfa1160a08e0.png)

**Comment by db0** [comment]
should be woirking now
