### ISSUE TITLE
Confession always adds 1 Gr , even if Blessed (printed) skill is 2

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#168]

**Comment by mmeldo** [comment]
Hi there. I have come across this one and thought why not fixing it myself since I am starting to learn some Python. Then, I thought why not start contributing. So, would that be ok to look at some of these issues?

**Comment by db0** [comment]
Ye go for it!

**Comment by mmeldo** [comment]
A lot of these issues is already fixed, so I guess I just mark them so they can be closed.
