### ISSUE TITLE
This is a holdup! Incorrect number of GR stolen is displayed

### ISSUE THREAD

**Issue by mysticpickle** [db0/Doomtown-Reloaded-OCTGN#25]
I had 1 GR remaining and my opponent played This is a Hold Up! on my Pearly's Palace (+3 GR income).  My 1 remaining GR was properly taken from me but the text box incorrectly displayed that "I did not have enough to steal so the 6 remaining GR was stolen instead."

**Comment by db0** [comment]
I cannot replicate this, have you seen it again since?

**Comment by mysticpickle** [comment]
hm nope not that many people play This is a Hold Up! so I haven't seen it since.  I'll try to get a screenshot next time I run into it.

**Comment by db0** [comment]
OK I'm closing this and we can re-open if it happens
