### ISSUE TITLE
Flamethrower placed bullet bonuses hard to see

### ISSUE THREAD

**Issue by mysticpickle** [db0/Doomtown-Reloaded-OCTGN#27]
When Flamer Thrower is used, the bullet bonuses are put on the Flamerthrower itself which is correct but really hard to see since goods are attached to a dude and behind them hiding the bullet bonues.  It'd be better if the Flame thrower put the bullets on the dude so we can visually see the bonus being added!

**Comment by db0** [comment]
Sorry but I don't want to start bending the rules for visibility, it'll just be a headache to keep track of it later and someone is going to report it as a bug anyway. Just press page-up or drag it a bit to the side on the flamethrower to make it visible,
