### ISSUE TITLE
[bug] When Mongwau uses his ability random hex gets discarded.

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#29]
I am pretty sure Hex Slingin' is bugged too in the same way, although I cannot test it now since OCTGN seems to be down, will update later on this issue.

**Comment by db0** [comment]
Did you target the hex to be discarded when you used his ability? In general it should be asking if you got more than 1 hex attached

**Comment by swider33** [comment]
Yes, it seems like the discarded hex is never the targeted one. I am going to test it properly as soon as OCTGN is up again, I will try to target all the hexes apart from one too.

**Comment by swider33** [comment]
Ok, tested it,  his ability discards the last attached spell. Hex Slingin' seems to work properly.

**Comment by db0** [comment]
Fixed
