### ISSUE TITLE
[feature request] The end of a shootout

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#35]
Could we receive an information which player started shootout at the end of a shootout ( who called who already displayed at the beginning of the shootout, displayed again at the end of it would be enough, possibly followed by don't forget to collect your bounty or similar message)? Quite often during long game it is very easy to forget who started shootout, very often both players assume it is the other one turn.

**Comment by db0** [comment]
You can tell my the attacker and defender colour. The Red one is always the attacking side, so they eiither did a job or called out.

**Comment by swider33** [comment]
True, but the problem arises when the shootout is long, everyone is focused on the gamepay and then someone presses f10 too early or  there is a litte banter after the shootout which also leads to situation where both players are uncertain who started it all.It is also true that I most probably wouldn't report a problem if I didn't have to play so often on a laptop with smallish screen, finding anything in a log is sometimes hard. Anyway it was just a suggestion, thanks for a quick answer.

**Comment by mysticpickle** [comment]
Yeah I can second swider's comment1  I often forget who started the shootout after a particularly involved lengthy shootout and I'll have to scroll up quite a bit searching for who made the callout and have be reminded or remind another person about who has the next noon play!
