### ISSUE TITLE
Mendoza takes payment before Kidnappin' is opposed.

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#41]
Should be after opposing. Should not pay if job is not opposed.

---

aetherial plays Kidnappin' from their hand.
:> aetherial uses Ramiro Mendoza to pay 1 Ghost Rock.
Ramiro Mendoza is now wanted by the law.
:> aetherial uses Kidnappin' to start a job marking Irving Patterson. Ramiro Mendoza is leading..
Irving Patterson is defending against this job. A shootout is breaking out!
:> mplain uses Irving Patterson to gain 1 Ghost Rock.
Ramiro Mendoza's wanted bounty increases to 2

**Comment by db0** [comment]
No, Mendoza joins the posse at the time of the job's creation, regardless of if they oppose
