### ISSUE TITLE
Mayor's Office - Error with proxy text

### ISSUE THREAD

**Issue by soulb1ight** [db0/Doomtown-Reloaded-OCTGN#53]
Printed card text for The Mayor's Office:
Private • Government
Controller Noon, Boot: Raise or lower the influence of a dude at this or an adjacent location by 1.

The Proxy Text for this card reads:
Public - Government

This issue also exists in Doomtown DB:
http://dtdb.co/find/?q=mayor%27s+office

**Comment by soulb1ight** [comment]
![mayor s office printed](https://cloud.githubusercontent.com/assets/11745280/6931458/726d4bf4-d7db-11e4-977e-f14d6e030370.jpg)
![mayor s office proxy](https://cloud.githubusercontent.com/assets/11745280/6931459/7270f286-d7db-11e4-99ea-9e83b92d54fd.jpg)

**Comment by soulb1ight** [comment]
Not sure if anything else has to happen for this fix.  Was the set.xml the only change that needed to be made?

**Comment by db0** [comment]
Yep
