### ISSUE TITLE
[bug] Bottom dealin' and empty deck (cards only on discard pile)

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#65]
Bottom dealin' freezes when there is 0 cards in a deck ( reshuffling doesn't work), I tried to reshuffle manually by taking control over my opponents discard pile, and his cards got reshuffled into mine deck not his.

**Comment by db0** [comment]
Fixed

**Comment by swider33** [comment]
Thank you. It is very late, I hope you didn't spend too much time on this
one :).

**Comment by db0** [comment]
Took me a bit to rework it but it's all good. I did a lot of other improvements as well. ;)

**Comment by swider33** [comment]
I was just reading a log :). I appeciate it.
