### ISSUE TITLE
bottom dealin' can't move cards because affected player doesn't own the card

### ISSUE THREAD

**Issue by mysticpickle** [db0/Doomtown-Reloaded-OCTGN#68]
After my opponent plays bottom dealin' on me, after the cards are removed the log lists error messages saying I cannot move a card because I don't own it.

![image](https://cloud.githubusercontent.com/assets/3962478/7548059/f22962e6-f5af-11e4-8824-94c214770fd1.png)

**Comment by db0** [comment]
Fixed
