### ISSUE TITLE
Shortcut guide and buttons.

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#7]
( I've read the changelog and noticed that you fixed the issues we talked about yesterday, I also realise that I shouldn't combine two different requests into one, but they are quite similar to each other. I also hope that you don't mind that I asked for additional feature rather then reported a bug).
I think it would be nice to have shortcut guide and how to draw hand guide available from the menu, they would work exactly as hand rank guide, and would be great help for new OCTGN players.
Also the buttons similar to those that are in ANR would be useful, examples of them are: "pass", "posse ready", "thinking".

**Comment by db0** [comment]
I remember you sent me a draft version but I can't find if you sent me a final version

**Comment by swider33** [comment]
I did send you improved version, and asked you for your feedback, thought
you really didn't like it so I never mentioned it again. I think the
improved version is good for new players, but only for them.
On 23 Jan 2015 23:11, "Divided by Zer0" <notifications@github.com> wrote:
>
> I remember you sent me a draft version but I can't find if you sent me a
final version

**Comment by db0** [comment]
You replied to github, so the attachment was lost. Can you send me a link or email me directly?

**Comment by swider33** [comment]
Here is the link: https://docs.google.com/presentation/d/1iiYZg0vRGDFQrp3YUitdiz11Y2m07MfVcuFwlS1Z4yE/edit#slide=id.p14

**Comment by db0** [comment]
Thanks, I'll publish it now

On Sat, Jan 24, 2015 at 12:20 AM, swider33 <notifications@github.com> wrote:

> Here is the link:
> https://docs.google.com/presentation/d/1iiYZg0vRGDFQrp3YUitdiz11Y2m07MfVcuFwlS1Z4yE/edit#slide=id.p14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/db0/Doomtown-Reloaded-OCTGN/issues/7#issuecomment-71283604>
> .
>



-- 
Personal haven @ http://dbzer0.com
--

**Comment by swider33** [comment]
Looking at it now, I would probably remove all shortcuts regarding setting up a game, also I think that mini guide ( that I copied from your installation guide) how to draw hands and redraw cards is necessary, markers shortcut guide possibly should become seperate document.

**Comment by db0** [comment]
Feel free to update it and lemme know. When I did the SW one, I just did a
second page just for the smart action ;)

On Sat, Jan 24, 2015 at 12:27 AM, swider33 <notifications@github.com> wrote:

> Looking at it now, I would probably remove all shortcuts regarding setting
> up a game, also I think that mini guide ( that I copied from your
> installation guide) how to draw hands and redraw cards is necessary,
> markers shortcut guide possibly should become seperate document.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/db0/Doomtown-Reloaded-OCTGN/issues/7#issuecomment-71284333>
> .
>



-- 
Personal haven @ http://dbzer0.com
--
