### ISSUE TITLE
[bug] Impossible to load a deck after OCTGN update.

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#71]
My OCTGN version just got updated, I didn't have a problem joining a game but this communicate appeared in a room log ( on joining a room): This game doesn't have a Script Version specified. Please contact the game developer.
After starting a game and loading a deck ( all without problems), when I move home card to a table rest of the cards stay in play hand ( I  quickly reinstalled everything and have the same problem).
I also tried to start a game I created with the same result.

**Comment by db0** [comment]
Yep latest OCTGN update broke almost all games. Gotta wait a bit
