### ISSUE TITLE
Update to 1.7

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#78]
According to a changelog this version should add NTB to a client, but when I tried to load a deck with new cards a game returned an error about corrupted file ( mplain has the same error).

**Comment by db0** [comment]
Do you see the new set in the deck editor of OCTGN?

**Comment by swider33** [comment]
Yes.

**Comment by db0** [comment]
This is then prolly because DTDB hasn't added the card GUIDs yet. I've sent them the XML. Until then you can make the deck in OCTGN.

**Comment by swider33** [comment]
Thanks.
