### ISSUE TITLE
Max Baine (Exp.1)

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#79]
How do i use this card?

It seems scripted, but I can't figure out how to use it. I target a dude in my hand and a location where Max is at, and press ctrl+Z on him, he boots and gets the used ability marker, but the dude is still in my hand, and the log gives an error message: "Need target (Dude)".

**Comment by db0** [comment]
Try to target the dude in your hand but not the location and press ctrl+Z

**Comment by mplain** [comment]
Nope, it doesn't work. Says I need a valid target: (Dude).

**Comment by db0** [comment]
Fixed
