### ISSUE TITLE
Items and cards that cause discard or ace other cards sometimes trigger on random cards

### ISSUE THREAD

**Issue by swider33** [db0/Doomtown-Reloaded-OCTGN#8]
Items and cards that cause discard or ace other cards sometimes trigger on random cards. Examples of items that are causing it: shotgun,coachwhip, hex slingin'. It happens quite often that if those items are used, the dude that has them on itself is discarded or aced alongside intended target of the card. Very often the goods card " refuses" to be reattached when a player tries to fix a bug manually.
 Also in some games deeds start to disappear from the map at random, I am not sure if it is connected to above mentioned bug, but I think so.

**Comment by db0** [comment]
Still didn't happen again?

**Comment by swider33** [comment]
I haven't noticed this email yesterday. I think the bug was created by
targeting more than one card when card's effect was discarding/aceing a
card. I haven't seen this bug snowballing since reporting it.  Constraining
a type and/or a number of cards targeted by a card that discards or aces
other cards might be a good idea. While it is quite easy to manualy reverse
a created problem , sometimes a card removed from the table, for instance a
huckster, has other cards attached to it that have various state ( booted /
unbooted), and recovering the state of all of those cards is sometimes hard.

**Comment by db0** [comment]
Cards are already constrained, but if you target two dudes with coachwhip
and one is wrong, then there's really nothing I can do

On Sat, Jan 24, 2015 at 1:19 PM, swider33 <notifications@github.com> wrote:

> I haven't noticed this email yesterday. I think the bug was created by
> targeting more than one card when card's effect was discarding/aceing a
> card. I haven't seen this bug snowballing since reporting it. Constraining
> a type and/or a number of cards targeted by a card that discards or aces
> other cards might be a good idea. While it is quite easy to manualy
> reverse
> a created problem , sometimes a card removed from the table, for instance
> a
> huckster, has other cards attached to it that have various state ( booted
> /
> unbooted), and recovering the state of all of those cards is sometimes
> hard.
> On 24 Jan 2015 11:09, "Divided by Zer0" <notifications@github.com> wrote:
>
> > Closed #8 <https://github.com/db0/Doomtown-Reloaded-OCTGN/issues/8>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/db0/Doomtown-Reloaded-OCTGN/issues/8#event-224139670>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/db0/Doomtown-Reloaded-OCTGN/issues/8#issuecomment-71314411>
> .
>



-- 
Personal haven @ http://dbzer0.com
--
