### ISSUE TITLE
Spirit Dance & The Pack Awakens don't work

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#85]
Say "This card is already in the shootout", don't spawn a token.

**Comment by mplain** [comment]
The Pack Awakens bring an unbooted token into a posse.
Since California Tax Office comes into play booted automatically, there probably is a way to script this, right?

**Comment by db0** [comment]
Game is not meant to handle two modifications of the token on creation. I'll need to create the code for it. Can you open a new ticket?
