### ISSUE TITLE
Xui Yin Chen & Yunxu Jiang don't give proper bonuses

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#86]
On ctrl+Z:
Xui Yin Chen gives Stud markers to everyone in the posse, but doesn't give +1 influence markers.
Yunxu Jiang does nothing (I know it's a train and not an ability, still making it scripted would help to keep track of what's going on).

**Comment by db0** [comment]
This is on purpose. There's no temporary shootout influence so you'd have to clear those manually after the shootout, and with Yunxu being a trait, it would be a pain to clear things when he leaves the shootout from pistol whips etc. Just keep track manually.
