### ISSUE TITLE
Bai Yang Chen's +1 production marker doesn't get removed after upkeep

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#90]

**Comment by db0** [comment]
Why should it?

**Comment by mplain** [comment]
If I don't remove them manually, they keep accumulating every time I press ctrl+Z, so next turn I don't pay any upkeep for him, and after that I [probably] start getting money. And it's easy to forget to remove the marker manually, and it leads to a lot of confusion.

**Comment by mplain** [comment]
Also it would be nice if you could make it so that the marker is removed automatically if Bai Yang Chen is hit with Flight of the Lepus during lowball, but I suspect that would be too complicated to implement =_=

**Comment by db0** [comment]
You don't have to press Ctrl+Z all the time. Just remove the marker if you move out of their home.
