### ISSUE TITLE
Sarah Meoquanee's ability is not automatic

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#91]
While making her join the posse isn't hard to do manually, the Used Ability marker would really help to keep track of whether her ability has been used this turn or not.

**Comment by mplain** [comment]
Now she gets the stud marker and the used ability marker, but doesn't join the location of the shootout, unlike many other cards that bring dudes into a posse. You intent to keep it that way, so that her ability doesn't actually require targeting?

Hey, thanks for finally fixing all that stuff, the game goes smoother now :)

**Comment by db0** [comment]
Yeah trying to figure out where the shootout is and place her in the right place would be a PITA. Thanks
