### ISSUE TITLE
108 Righteous Bandits' outfit works weirdly

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#93]
I target one dude, target the other one, ctrl+Z on the outfit, it asks to which dude's location I'm going, and then half the time this same dude goes to his own location. Game should be able to recognize that it's the other dude who's going to the chosen dude's location.

**Comment by db0** [comment]
Don't target the dude you move to. It will always ask you anyway.

**Comment by mplain** [comment]
If I target only one dude, it's not asking me anything, it just moves that dude to his own location.
