### ISSUE TITLE
Sword of the Spirit

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#97]
Places the stud marker on the spell itself, not the targeted dude.

**Comment by db0** [comment]
IIRC you need to target the weapon.

**Comment by mplain** [comment]
Well, we didn't figure it out, I think it's somewhat un-intuitive, since the spell says "choose a dude".

**Comment by swider33** [comment]
Also the marker says 1 stud, there is nothing about immunity from spells. Also agree with Mplain that targeting the weapon is not intuitive.

**Comment by mplain** [comment]
Also this spell boots itself when used, but its cost doesn't include booting.
(thanks @jayjester)
