### ISSUE TITLE
Nathan Shane

### ISSUE THREAD

**Issue by mplain** [db0/Doomtown-Reloaded-OCTGN#98]
Shane's ability places the revealed card into ScriptingPile, but if it's not an action then the card stays there and doesn't return to hand.

**Comment by soulb1ight** [comment]
If Shane is Pinned Down and uses his ability, the game sees him as having -3 bullets which affects how many cards he can see.  Since he is not chosen as the shooter, the bullet penalty should not apply yet.

**Comment by db0** [comment]
Hm, weird. Is this if you close the window with the 'X'?
